jobs:
  build:
    docker:
      - image: cimg/python:3.8
    parallelism: 14
    steps:
      - checkout
      - run:
          name: apoppo
          environment:
            PGPORT: 5433
          command: |
            counter=1; while [ $counter -le 3310 ]; do echo $counter; ((counter++)); clear; done
